export const exercises = [
  {
    key: "Step Jacks",
    value: "Step Jacks",
    text: "Step Jacks",
    ExerciseName: "Step Jacks",
    src: "https://www.youtube.com/watch?v=JHdVMkRBuRA",
  },
  {
    key: "Raised Arms Circles",
    value: "Raised Arms Circles",
    text: "Raised Arms Circles",
    ExerciseName: "Raised Arms Circles",
    src: "https://www.youtube.com/watch?v=D40wm6vbI_0",
  },
  {
    key: "Bicep Extensions",
    value: "Bicep Extensions",
    text: "Bicep Extensions",
    ExerciseName: "Bicep Extensions",
    src: "https://www.youtube.com/watch?v=l5dfkW6w5qI",
  },
  {
    key: "Standing Shoulder Taps",
    value: "Standing Shoulder Taps",
    text: "Standing Shoulder Taps",
    ExerciseName: "Standing Shoulder Taps",
    src: "https://www.youtube.com/watch?v=j9NPpdmG89s",
  },
  {
    key: "Micro Chest Expansions",
    value: "Micro Chest Expansions",
    text: "Micro Chest Expansions",
    ExerciseName: "Micro Chest Expansions",
    src: "https://www.youtube.com/watch?v=77FNvJPaVjs",
  },
  {
    key: "Side Bends",
    value: "Side Bends",
    text: "Side Bends",
    ExerciseName: "Side Bends",
    src: "https://www.youtube.com/watch?v=uWLFCRHU0Og",
  },
  {
    key: "Stacked Push-Ups",
    value: "Stacked Push-Ups",
    text: "Stacked Push-Ups",
    ExerciseName: "Stacked Push-Ups",
    src: "https://www.youtube.com/watch?v=YEDCkJ-Uv7c",
  },
  {
    key: "Staggered Push-Ups",
    value: "Staggered Push-Ups",
    text: "Staggered Push-Ups",
    ExerciseName: "Staggered Push-Ups",
    src: "https://www.youtube.com/watch?v=FO3MZNFQS28",
  },
  {
    key: "Diver Push-Ups",
    value: "Diver Push-Ups",
    text: "Diver Push-Ups",
    ExerciseName: "Diver Push-Ups",
    src: "https://www.youtube.com/watch?v=tQbcc27zjiA",
  },
  {
    key: "Raised Leg Push-Ups",
    value: "Raised Leg Push-Ups",
    text: "Raised Leg Push-Ups",
    ExerciseName: "Raised Leg Push-Ups",
    src: "https://www.youtube.com/watch?v=XA8T_bHHkl0",
  },
  {
    key: "Squat Hold Calf Raises",
    value: "Squat Hold Calf Raises",
    text: "Squat Hold Calf Raises",
    ExerciseName: "Squat Hold Calf Raises",
    src: "https://www.youtube.com/watch?v=wYoE11arXIw",
  },
  {
    key: "Squat Cross Steps",
    value: "Squat Cross Steps",
    text: "Squat Cross Steps",
    ExerciseName: "Squat Cross Steps",
    src: "https://www.youtube.com/watch?v=8JLMA-Z5S1o",
  },
  {
    key: "Sprinter Lunges",
    value: "Sprinter Lunges",
    text: "Sprinter Lunges",
    ExerciseName: "Sprinter Lunges",
    src: "https://www.youtube.com/watch?v=kaFs0XcgUfo",
  },
  {
    key: "Split Jacks",
    value: "Split Jacks",
    text: "Split Jacks",
    ExerciseName: "Split Jacks",
    src: "https://www.youtube.com/watch?v=83cVgok6KrI",
  },
  {
    key: "Reverse Plank Kicks",
    value: "Reverse Plank Kicks",
    text: "Reverse Plank Kicks",
    ExerciseName: "Reverse Plank Kicks",
    src: "https://www.youtube.com/watch?v=3eIPmCV_1HM",
  },
  {
    key: "Reverse Lunges",
    value: "Reverse Lunges",
    text: "Reverse Lunges",
    ExerciseName: "Reverse Lunges",
    src: "https://www.youtube.com/watch?v=-Q_2HR5OhEY",
  },
  {
    key: "Reverse Lunge Knee Taps",
    value: "Reverse Lunge Knee Taps",
    text: "Reverse Lunge Knee Taps",
    ExerciseName: "Reverse Lunge Knee Taps",
    src: "https://www.youtube.com/watch?v=PnjYoDKj32c",
  },
  {
    key: "March Jacks",
    value: "March Jacks",
    text: "March Jacks",
    ExerciseName: "March Jacks",
    src: "https://www.youtube.com/watch?v=qIDC7Ttfjn0",
  },
  {
    key: "Lunge Step-Ups",
    value: "Lunge Step-Ups",
    text: "Lunge Step-Ups",
    ExerciseName: "Lunge Step-Ups",
    src: "https://www.youtube.com/watch?v=KM6-6xTRpow",
  },
  {
    key: "Lasso Twists",
    value: "Lasso Twists",
    text: "Lasso Twists",
    ExerciseName: "Lasso Twists",
    src: "https://www.youtube.com/watch?v=OjFo600wGK4",
  },
  {
    key: "Jump Knee-Tucks",
    value: "Jump Knee-Tucks",
    text: "Jump Knee-Tucks",
    ExerciseName: "Jump Knee-Tucks",
    src: "https://www.youtube.com/watch?v=ArZXCfbjxWs",
  },
  {
    key: "Side-to-Side Hops - feet Together",
    value: "Side-to-Side Hops - feet Together",
    text: "Side-to-Side Hops - feet Together",
    ExerciseName: "Side-to-Side Hops - feet Together",
    src: "https://www.youtube.com/watch?v=0ZxLHEKzBp4",
  },
  {
    key: "Side-to-Side Hops",
    value: "Side-to-Side Hops",
    text: "Side-to-Side Hops",
    ExerciseName: "Side-to-Side Hops",
    src: "https://www.youtube.com/watch?v=NTqBhdYuT6M",
  },
  {
    key: "Hops on the Spot",
    value: "Hops on the Spot",
    text: "Hops on the Spot",
    ExerciseName: "Hops on the Spot",
    src: "https://www.youtube.com/watch?v=42DO_okRZ1Q",
  },
  {
    key: "Hops - Ape",
    value: "Hops - Ape",
    text: "Hops - Ape",
    ExerciseName: "Hops - Ape",
    src: "https://www.youtube.com/watch?v=XG6eVjFp0hw",
  },
  {
    key: "High Squats",
    value: "High Squats",
    text: "High Squats",
    ExerciseName: "High Squats",
    src: "https://www.youtube.com/watch?v=iOJWztzaSlk",
  },
  {
    key: "High Knees",
    value: "High Knees",
    text: "High Knees",
    ExerciseName: "High Knees",
    src: "https://www.youtube.com/watch?v=DfjpR6dzLVg",
  },
  {
    key: "Get-Ups",
    value: "Get-Ups",
    text: "Get-Ups",
    ExerciseName: "Get-Ups",
    src: "https://www.youtube.com/watch?v=n47X4HOhfUk",
  },
  {
    key: "Full Bridges",
    value: "Full Bridges",
    text: "Full Bridges",
    ExerciseName: "Full Bridges",
    src: "https://www.youtube.com/watch?v=p6j00E71rvE",
  },
  {
    key: "Full Bridge + Reach",
    value: "Full Bridge + Reach",
    text: "Full Bridge + Reach",
    ExerciseName: "Full Bridge + Reach",
    src: "https://www.youtube.com/watch?v=Js_-S-Qcqdc",
  },
  {
    key: "Fly Steps",
    value: "Fly Steps",
    text: "Fly Steps",
    ExerciseName: "Fly Steps",
    src: "https://www.youtube.com/watch?v=pHPNrrcMobE",
  },
  {
    key: "Flow Steps",
    value: "Flow Steps",
    text: "Flow Steps",
    ExerciseName: "Flow Steps",
    src: "https://www.youtube.com/watch?v=Zj_I4lE_3uM",
  },
  {
    key: "Burpees with Rotations",
    value: "Burpees with Rotations",
    text: "Burpees with Rotations",
    ExerciseName: "Burpees with Rotations",
    src: "https://www.youtube.com/watch?v=aMD25OIumts",
  },
  {
    key: "Burpees with a Push-Up",
    value: "Burpees with a Push-Up",
    text: "Burpees with a Push-Up",
    ExerciseName: "Burpees with a Push-Up",
    src: "https://www.youtube.com/watch?v=ZQzikdjmkKg",
  },
  {
    key: "Burpees - Basic",
    value: "Burpees - Basic",
    text: "Burpees - Basic",
    ExerciseName: "Burpees - Basic",
    src: "https://www.youtube.com/watch?v=mG0iaoLM2vc",
  },
  {
    key: "Burpees",
    value: "Burpees",
    text: "Burpees",
    ExerciseName: "Burpees",
    src: "https://www.youtube.com/watch?v=E-Oc0zjeqWo",
  },
  {
    key: "Side Jacks",
    value: "Side Jacks",
    text: "Side Jacks",
    ExerciseName: "Side Jacks",
    src: "https://www.youtube.com/watch?v=xnY040imnsE",
  },
  {
    key: "Jump Cross Punches",
    value: "Jump Cross Punches",
    text: "Jump Cross Punches",
    ExerciseName: "Jump Cross Punches",
    src: "https://www.youtube.com/watch?v=TaOit8L53QI",
  },
  {
    key: "Single Leg Bridges",
    value: "Single Leg Bridges",
    text: "Single Leg Bridges",
    ExerciseName: "Single Leg Bridges",
    src: "https://www.youtube.com/watch?v=SNfgW5r0nOo",
  },
  {
    key: "Push-Ups / Wide Grip",
    value: "Push-Ups / Wide Grip",
    text: "Push-Ups / Wide Grip",
    ExerciseName: "Push-Ups / Wide Grip",
    src: "https://www.youtube.com/watch?v=1Y8pTxdwf3M",
  },
  {
    key: "Push-Ups / Close Grip",
    value: "Push-Ups / Close Grip",
    text: "Push-Ups / Close Grip",
    ExerciseName: "Push-Ups / Close Grip",
    src: "https://www.youtube.com/watch?v=SwoNNo4W1OU",
  },
  {
    key: "Push-Ups",
    value: "Push-Ups",
    text: "Push-Ups",
    ExerciseName: "Push-Ups",
    src: "https://www.youtube.com/watch?v=v9LABVJzv8A",
  },
  {
    key: "Plank Punches",
    value: "Plank Punches",
    text: "Plank Punches",
    ExerciseName: "Plank Punches",
    src: "https://www.youtube.com/watch?v=zzauMwuTFUg",
  },
  {
    key: "Windshield Wipers",
    value: "Windshield Wipers",
    text: "Windshield Wipers",
    ExerciseName: "Windshield Wipers",
    src: "https://www.youtube.com/watch?v=3npJSSGOpXg",
  },
  {
    key: "V-Ups",
    value: "V-Ups",
    text: "V-Ups",
    ExerciseName: "V-Ups",
    src: "https://www.youtube.com/watch?v=-JIwvMSk4vo",
  },
  {
    key: "Twists",
    value: "Twists",
    text: "Twists",
    ExerciseName: "Twists",
    src: "https://www.youtube.com/watch?v=h6TY6N1B7BA",
  },
  {
    key: "Sumo Squats",
    value: "Sumo Squats",
    text: "Sumo Squats",
    ExerciseName: "Sumo Squats",
    src: "https://www.youtube.com/watch?v=rmEVorjxBWs",
  },
  {
    key: "Superman Into V-Ups",
    value: "Superman Into V-Ups",
    text: "Superman Into V-Ups",
    ExerciseName: "Superman Into V-Ups",
    src: "https://www.youtube.com/watch?v=Z7BQY661ImQ",
  },
  {
    key: "Squat Step-Ups",
    value: "Squat Step-Ups",
    text: "Squat Step-Ups",
    ExerciseName: "Squat Step-Ups",
    src: "https://www.youtube.com/watch?v=wRqGReHI3oo",
  },
  {
    key: "Speed Skater Slides",
    value: "Speed Skater Slides",
    text: "Speed Skater Slides",
    ExerciseName: "Speed Skater Slides",
    src: "https://www.youtube.com/watch?v=JVUjxCXDZUc",
  },
  {
    key: "Skiers",
    value: "Skiers",
    text: "Skiers",
    ExerciseName: "Skiers",
    src: "https://www.youtube.com/watch?v=srDMn6iNrsc",
  },
  {
    key: "Sit-Up Elbow Strikes",
    value: "Sit-Up Elbow Strikes",
    text: "Sit-Up Elbow Strikes",
    ExerciseName: "Sit-Up Elbow Strikes",
    src: "https://www.youtube.com/watch?v=WNi392v4mJA",
  },
  {
    key: "Sit-Up Punches",
    value: "Sit-Up Punches",
    text: "Sit-Up Punches",
    ExerciseName: "Sit-Up Punches",
    src: "https://www.youtube.com/watch?v=y6lW-GmjhvQ",
  },
  {
    key: "Sitting Punches",
    value: "Sitting Punches",
    text: "Sitting Punches",
    ExerciseName: "Sitting Punches",
    src: "https://www.youtube.com/watch?v=BqIryHLrTAg",
  },
  {
    key: "Side Plank Knee Taps",
    value: "Side Plank Knee Taps",
    text: "Side Plank Knee Taps",
    ExerciseName: "Side Plank Knee Taps",
    src: "https://www.youtube.com/watch?v=CsP26894Fw8",
  },
  {
    key: "Side Star Planks",
    value: "Side Star Planks",
    text: "Side Star Planks",
    ExerciseName: "Side Star Planks",
    src: "https://www.youtube.com/watch?v=ioXJRP6HdbU",
  },
  {
    key: "Side Jackknives",
    value: "Side Jackknives",
    text: "Side Jackknives",
    ExerciseName: "Side Jackknives",
    src: "https://www.youtube.com/watch?v=6sHRqhKCJeA",
  },
  {
    key: "Side Arm Raises",
    value: "Side Arm Raises",
    text: "Side Arm Raises",
    ExerciseName: "Side Arm Raises",
    src: "https://www.youtube.com/watch?v=ww0r9xZunDM",
  },
  {
    key: "Shrimp Squats",
    value: "Shrimp Squats",
    text: "Shrimp Squats",
    ExerciseName: "Shrimp Squats",
    src: "https://www.youtube.com/watch?v=XUDOpNWhVr0",
  },
  {
    key: "Rotations",
    value: "Rotations",
    text: "Rotations",
    ExerciseName: "Rotations",
    src: "https://www.youtube.com/watch?v=NlwB3U883Zo",
  },
  {
    key: "Roll-Ups",
    value: "Roll-Ups",
    text: "Roll-Ups",
    ExerciseName: "Roll-Ups",
    src: "https://www.youtube.com/watch?v=baHy6u93bfQ",
  },
  {
    key: "Raised Leg Crunches",
    value: "Raised Leg Crunches",
    text: "Raised Leg Crunches",
    ExerciseName: "Raised Leg Crunches",
    src: "https://www.youtube.com/watch?v=yut42mEQXTk",
  },
  {
    key: "Raised Leg Circles",
    value: "Raised Leg Circles",
    text: "Raised Leg Circles",
    ExerciseName: "Raised Leg Circles",
    src: "https://www.youtube.com/watch?v=2Vwfd-Q8MDs",
  },
  {
    key: "Raised Arm Circles",
    value: "Raised Arm Circles",
    text: "Raised Arm Circles",
    ExerciseName: "Raised Arm Circles",
    src: "https://www.youtube.com/watch?v=g3oaRLbo-yw",
  },
  {
    key: "Pulse-Ups",
    value: "Pulse-Ups",
    text: "Pulse-Ups",
    ExerciseName: "Pulse-Ups",
    src: "https://www.youtube.com/watch?v=Dv3G4WOFG5A",
  },
  {
    key: "Pop-Up Tripod",
    value: "Pop-Up Tripod",
    text: "Pop-Up Tripod",
    ExerciseName: "Pop-Up Tripod",
    src: "https://www.youtube.com/watch?v=wG9634VCjck",
  },
  {
    key: "Plank Walk-Outs",
    value: "Plank Walk-Outs",
    text: "Plank Walk-Outs",
    ExerciseName: "Plank Walk-Outs",
    src: "https://www.youtube.com/watch?v=Ao-nV3IdINQ",
  },
  {
    key: "Plank Side Crunches",
    value: "Plank Side Crunches",
    text: "Plank Side Crunches",
    ExerciseName: "Plank Side Crunches",
    src: "https://www.youtube.com/watch?v=O8NJySgPwWE",
  },
  {
    key: "Pistol Squats  / Half Way",
    value: "Pistol Squats  / Half Way",
    text: "Pistol Squats  / Half Way",
    ExerciseName: "Pistol Squats  / Half Way",
    src: "https://www.youtube.com/watch?v=sHpBSJeHFMs",
  },
  {
    key: "L Sit-Ups",
    value: "L Sit-Ups",
    text: "L Sit-Ups",
    ExerciseName: "L Sit-Ups",
    src: "https://www.youtube.com/watch?v=GmrgJGwmBFY",
  },
  {
    key: "Leg Raises",
    value: "Leg Raises",
    text: "Leg Raises",
    ExerciseName: "Leg Raises",
    src: "https://www.youtube.com/watch?v=_OQaO65Vdzs",
  },
  {
    key: "Lawnmowers",
    value: "Lawnmowers",
    text: "Lawnmowers",
    ExerciseName: "Lawnmowers",
    src: "https://www.youtube.com/watch?v=f2o9-Lq16Ao",
  },
  {
    key: "Knee-to-Elbows",
    value: "Knee-to-Elbows",
    text: "Knee-to-Elbows",
    ExerciseName: "Knee-to-Elbows",
    src: "https://www.youtube.com/watch?v=ZL9Y-IIedb0",
  },
  {
    key: "Jumping Ts",
    value: "Jumping Ts",
    text: "Jumping Ts",
    ExerciseName: "Jumping Ts",
    src: "https://www.youtube.com/watch?v=bdTT0sz5s_c",
  },
  {
    key: "Jumping Lunges",
    value: "Jumping Lunges",
    text: "Jumping Lunges",
    ExerciseName: "Jumping Lunges",
    src: "https://www.youtube.com/watch?v=Kq5lZ4o26Ho",
  },
  {
    key: "High Crunches",
    value: "High Crunches",
    text: "High Crunches",
    ExerciseName: "High Crunches",
    src: "https://www.youtube.com/watch?v=W-5q50TkMio",
  },
  {
    key: "Heel Taps",
    value: "Heel Taps",
    text: "Heel Taps",
    ExerciseName: "Heel Taps",
    src: "https://www.youtube.com/watch?v=jfXcyLTuKP4",
  },
  {
    key: "Half Wipers",
    value: "Half Wipers",
    text: "Half Wipers",
    ExerciseName: "Half Wipers",
    src: "https://www.youtube.com/watch?v=emrs9ZjM3FA",
  },
  {
    key: "Half Squat Walk",
    value: "Half Squat Walk",
    text: "Half Squat Walk",
    ExerciseName: "Half Squat Walk",
    src: "https://www.youtube.com/watch?v=Z-Agg8x8O7k",
  },
  {
    key: "Half Squat Ts",
    value: "Half Squat Ts",
    text: "Half Squat Ts",
    ExerciseName: "Half Squat Ts",
    src: "https://www.youtube.com/watch?v=2r70AJlDJLQ",
  },
  {
    key: "Crunch Kicks",
    value: "Crunch Kicks",
    text: "Crunch Kicks",
    ExerciseName: "Crunch Kicks",
    src: "https://www.youtube.com/watch?v=n6NYu9d7uwk",
  },
  {
    key: "Butt-Ups",
    value: "Butt-Ups",
    text: "Butt-Ups",
    ExerciseName: "Butt-Ups",
    src: "https://www.youtube.com/watch?v=fKbwSN6hwxw",
  },
  {
    key: "Butterfly Sit-Ups",
    value: "Butterfly Sit-Ups",
    text: "Butterfly Sit-Ups",
    ExerciseName: "Butterfly Sit-Ups",
    src: "https://www.youtube.com/watch?v=pXN6y4uUuMw",
  },
  {
    key: "Bodyweight Bicep Curls",
    value: "Bodyweight Bicep Curls",
    text: "Bodyweight Bicep Curls",
    ExerciseName: "Bodyweight Bicep Curls",
    src: "https://www.youtube.com/watch?v=2nuVRRDO4gc",
  },
  {
    key: "Air Bike Crunches",
    value: "Air Bike Crunches",
    text: "Air Bike Crunches",
    ExerciseName: "Air Bike Crunches",
    src: "https://www.youtube.com/watch?v=jKT7-9L935g",
  },
  {
    key: "Double Chest Expansions",
    value: "Double Chest Expansions",
    text: "Double Chest Expansions",
    ExerciseName: "Double Chest Expansions",
    src: "https://www.youtube.com/watch?v=g-1mM5SuKQ8",
  },
  {
    key: "Chest Expansions",
    value: "Chest Expansions",
    text: "Chest Expansions",
    ExerciseName: "Chest Expansions",
    src: "https://www.youtube.com/watch?v=El_Sj5hisSs",
  },
  {
    key: "Balance Side Lunges",
    value: "Balance Side Lunges",
    text: "Balance Side Lunges",
    ExerciseName: "Balance Side Lunges",
    src: "https://www.youtube.com/watch?v=mXEiJQPqqgE",
  },
  {
    key: "Balance Back Kicks",
    value: "Balance Back Kicks",
    text: "Balance Back Kicks",
    ExerciseName: "Balance Back Kicks",
    src: "https://www.youtube.com/watch?v=GlRf9STzF7k",
  },
  {
    key: "Elbow Strikes / Step-Ins",
    value: "Elbow Strikes / Step-Ins",
    text: "Elbow Strikes / Step-Ins",
    ExerciseName: "Elbow Strikes / Step-Ins",
    src: "https://www.youtube.com/watch?v=N9vYpmtCQ2U",
  },
  {
    key: "Upward Palm Strikes",
    value: "Upward Palm Strikes",
    text: "Upward Palm Strikes",
    ExerciseName: "Upward Palm Strikes",
    src: "https://www.youtube.com/watch?v=UaQEwCyunC0",
  },
  {
    key: "Upward Elbow Strike / Step-In",
    value: "Upward Elbow Strike / Step-In",
    text: "Upward Elbow Strike / Step-In",
    ExerciseName: "Upward Elbow Strike / Step-In",
    src: "https://www.youtube.com/watch?v=igsK29nb-hY",
  },
  {
    key: "Upward Elbow Strikes",
    value: "Upward Elbow Strikes",
    text: "Upward Elbow Strikes",
    ExerciseName: "Upward Elbow Strikes",
    src: "https://www.youtube.com/watch?v=9Vy5BfIlr-8",
  },
  {
    key: "Uppercut",
    value: "Uppercut",
    text: "Uppercut",
    ExerciseName: "Uppercut",
    src: "https://www.youtube.com/watch?v=WRd5zsPixIY",
  },
  {
    key: "Squat + Uppercut",
    value: "Squat + Uppercut",
    text: "Squat + Uppercut",
    ExerciseName: "Squat + Uppercut",
    src: "https://www.youtube.com/watch?v=KroPA68xBWo",
  },
  {
    key: "Squat + Turning Kick / Back Leg",
    value: "Squat + Turning Kick / Back Leg",
    text: "Squat + Turning Kick / Back Leg",
    ExerciseName: "Squat + Turning Kick / Back Leg",
    src: "https://www.youtube.com/watch?v=gNU_G_oGiwg",
  },
  {
    key: "Squat + Turning Kick",
    value: "Squat + Turning Kick",
    text: "Squat + Turning Kick",
    ExerciseName: "Squat + Turning Kick",
    src: "https://www.youtube.com/watch?v=5T12EmldUIY",
  },
  {
    key: "Squat + Side Kick",
    value: "Squat + Side Kick",
    text: "Squat + Side Kick",
    ExerciseName: "Squat + Side Kick",
    src: "https://www.youtube.com/watch?v=qzyFuvvurSM",
  },
  {
    key: "Squat + Hook",
    value: "Squat + Hook",
    text: "Squat + Hook",
    ExerciseName: "Squat + Hook",
    src: "https://www.youtube.com/watch?v=yE7l9EovL3E",
  },
  {
    key: "Squat Hold Punches",
    value: "Squat Hold Punches",
    text: "Squat Hold Punches",
    ExerciseName: "Squat Hold Punches",
    src: "https://www.youtube.com/watch?v=H29dYPRZNCE",
  },
  {
    key: "Squat + Front Kick",
    value: "Squat + Front Kick",
    text: "Squat + Front Kick",
    ExerciseName: "Squat + Front Kick",
    src: "https://www.youtube.com/watch?v=B7wTCQHAOC4",
  },
  {
    key: "Speed Bag Punches",
    value: "Speed Bag Punches",
    text: "Speed Bag Punches",
    ExerciseName: "Speed Bag Punches",
    src: "https://www.youtube.com/watch?v=8lDhhrj-odk",
  },
  {
    key: "Side-to-Side Lunges",
    value: "Side-to-Side Lunges",
    text: "Side-to-Side Lunges",
    ExerciseName: "Side-to-Side Lunges",
    src: "https://www.youtube.com/watch?v=KXoVm0WXcfE",
  },
  {
    key: "Side Lunges",
    value: "Side Lunges",
    text: "Side Lunges",
    ExerciseName: "Side Lunges",
    src: "https://www.youtube.com/watch?v=dTGZS-WCH4U",
  },
  {
    key: "Side Chops",
    value: "Side Chops",
    text: "Side Chops",
    ExerciseName: "Side Chops",
    src: "https://www.youtube.com/watch?v=LkAIHkKXYB4",
  },
  {
    key: "Push-Up + Jab + Cross",
    value: "Push-Up + Jab + Cross",
    text: "Push-Up + Jab + Cross",
    ExerciseName: "Push-Up + Jab + Cross",
    src: "https://www.youtube.com/watch?v=hUXxsuNqGtE",
  },
  {
    key: "Push Strikes",
    value: "Push Strikes",
    text: "Push Strikes",
    ExerciseName: "Push Strikes",
    src: "https://www.youtube.com/watch?v=GxZnA9hoIbE",
  },
  {
    key: "Punches / Straight",
    value: "Punches / Straight",
    text: "Punches / Straight",
    ExerciseName: "Punches / Straight",
    src: "https://www.youtube.com/watch?v=M_4Vt5lfEUE",
  },
  {
    key: "Palm Strikes",
    value: "Palm Strikes",
    text: "Palm Strikes",
    ExerciseName: "Palm Strikes",
    src: "https://www.youtube.com/watch?v=E2Afdzdc-7E",
  },
  {
    key: "Overhead Punches",
    value: "Overhead Punches",
    text: "Overhead Punches",
    ExerciseName: "Overhead Punches",
    src: "https://www.youtube.com/watch?v=UPV4156lSyc",
  },
  {
    key: "Outward Knife Hand Strikes",
    value: "Outward Knife Hand Strikes",
    text: "Outward Knife Hand Strikes",
    ExerciseName: "Outward Knife Hand Strikes",
    src: "https://www.youtube.com/watch?v=hvW4IPvBU3E",
  },
  {
    key: "Lunge Push Strikes",
    value: "Lunge Push Strikes",
    text: "Lunge Push Strikes",
    ExerciseName: "Lunge Push Strikes",
    src: "https://www.youtube.com/watch?v=WnuS0MLpLDA",
  },
  {
    key: "Lunge Punches",
    value: "Lunge Punches",
    text: "Lunge Punches",
    ExerciseName: "Lunge Punches",
    src: "https://www.youtube.com/watch?v=bdzrzvqcyBc",
  },
  {
    key: "Lunge Kicks",
    value: "Lunge Kicks",
    text: "Lunge Kicks",
    ExerciseName: "Lunge Kicks",
    src: "https://www.youtube.com/watch?v=T_PA0dpL86M",
  },
  {
    key: "Low Turning Kicks",
    value: "Low Turning Kicks",
    text: "Low Turning Kicks",
    ExerciseName: "Low Turning Kicks",
    src: "https://www.youtube.com/watch?v=QE_JNPqW9_Y",
  },
  {
    key: "Low Turning Kick / Back Leg",
    value: "Low Turning Kick / Back Leg",
    text: "Low Turning Kick / Back Leg",
    ExerciseName: "Low Turning Kick / Back Leg",
    src: "https://www.youtube.com/watch?v=fSz6eTEkHRM",
  },
  {
    key: "Knife Hand Strike / Back Hand",
    value: "Knife Hand Strike / Back Hand",
    text: "Knife Hand Strike / Back Hand",
    ExerciseName: "Knife Hand Strike / Back Hand",
    src: "https://www.youtube.com/watch?v=Y8NqJiaTR6Q",
  },
  {
    key: "Knife Hand Strike",
    value: "Knife Hand Strike",
    text: "Knife Hand Strike",
    ExerciseName: "Knife Hand Strike",
    src: "https://www.youtube.com/watch?v=wO_WUzVXyWc",
  },
  {
    key: "Knee Strike + Turning Kick + Side Kick",
    value: "Knee Strike + Turning Kick + Side Kick",
    text: "Knee Strike + Turning Kick + Side Kick",
    ExerciseName: "Knee Strike + Turning Kick + Side Kick",
    src: "https://www.youtube.com/watch?v=8UPuSGBGsmg",
  },
  {
    key: "Knee Strike + Elbow Strike",
    value: "Knee Strike + Elbow Strike",
    text: "Knee Strike + Elbow Strike",
    ExerciseName: "Knee Strike + Elbow Strike",
    src: "https://www.youtube.com/watch?v=jOrjXxe6ITw",
  },
  {
    key: "Knee Strikes / Back Leg",
    value: "Knee Strikes / Back Leg",
    text: "Knee Strikes / Back Leg",
    ExerciseName: "Knee Strikes / Back Leg",
    src: "https://www.youtube.com/watch?v=xQD-O5Y-qrs",
  },
  {
    key: "Knee Strikes",
    value: "Knee Strikes",
    text: "Knee Strikes",
    ExerciseName: "Knee Strikes",
    src: "https://www.youtube.com/watch?v=RBiqNyxcnco",
  },
  {
    key: "Jab + Jab + Cross + Hook",
    value: "Jab + Jab + Cross + Hook",
    text: "Jab + Jab + Cross + Hook",
    ExerciseName: "Jab + Jab + Cross + Hook",
    src: "https://www.youtube.com/watch?v=JGExGAmVvBk",
  },
  {
    key: "Jab + Jab + Cross",
    value: "Jab + Jab + Cross",
    text: "Jab + Jab + Cross",
    ExerciseName: "Jab + Jab + Cross",
    src: "https://www.youtube.com/watch?v=VxQWbxaV_9w",
  },
  {
    key: "Jab + Cross + Jab + Turning Kick",
    value: "Jab + Cross + Jab + Turning Kick",
    text: "Jab + Cross + Jab + Turning Kick",
    ExerciseName: "Jab + Cross + Jab + Turning Kick",
    src: "https://www.youtube.com/watch?v=9CHcm-5Aej4",
  },
  {
    key: "Jab + Cross + Jab + Double Turning Kicks",
    value: "Jab + Cross + Jab + Double Turning Kicks",
    text: "Jab + Cross + Jab + Double Turning Kicks",
    ExerciseName: "Jab + Cross + Jab + Double Turning Kicks",
    src: "https://www.youtube.com/watch?v=P8Q7pbPbNH0",
  },
  {
    key: "Jab + Cross + Jab + Double Side Kicks",
    value: "Jab + Cross + Jab + Double Side Kicks",
    text: "Jab + Cross + Jab + Double Side Kicks",
    ExerciseName: "Jab + Cross + Jab + Double Side Kicks",
    src: "https://www.youtube.com/watch?v=HWWE_5tE8VQ",
  },
  {
    key: "Jab + Cross",
    value: "Jab + Cross",
    text: "Jab + Cross",
    ExerciseName: "Jab + Cross",
    src: "https://www.youtube.com/watch?v=7S-FSrHUN1A",
  },
  {
    key: "Infinity Circles",
    value: "Infinity Circles",
    text: "Infinity Circles",
    ExerciseName: "Infinity Circles",
    src: "https://www.youtube.com/watch?v=FzJRBtvvYGY",
  },
  {
    key: "Infinity Chops",
    value: "Infinity Chops",
    text: "Infinity Chops",
    ExerciseName: "Infinity Chops",
    src: "https://www.youtube.com/watch?v=q4CKZ7OI6Ps",
  },
  {
    key: "Hooks",
    value: "Hooks",
    text: "Hooks",
    ExerciseName: "Hooks",
    src: "https://www.youtube.com/watch?v=4VOcf7j4VTM",
  },
  {
    key: "Elbow Strikes",
    value: "Elbow Strikes",
    text: "Elbow Strikes",
    ExerciseName: "Elbow Strikes",
    src: "https://www.youtube.com/watch?v=ujppQiig9CU",
  },
  {
    key: "Drop Back Kicks",
    value: "Drop Back Kicks",
    text: "Drop Back Kicks",
    ExerciseName: "Drop Back Kicks",
    src: "https://www.youtube.com/watch?v=ftfpTRfcrqI",
  },
  {
    key: "Downward Block Backfist",
    value: "Downward Block Backfist",
    text: "Downward Block Backfist",
    ExerciseName: "Downward Block Backfist",
    src: "https://www.youtube.com/watch?v=-H41KeE1QYI",
  },
  {
    key: "Double Side Kick / Side-to-Side",
    value: "Double Side Kick / Side-to-Side",
    text: "Double Side Kick / Side-to-Side",
    ExerciseName: "Double Side Kick / Side-to-Side",
    src: "https://www.youtube.com/watch?v=c7oF6PoDVZw",
  },
  {
    key: "Double Side Kick",
    value: "Double Side Kick",
    text: "Double Side Kick",
    ExerciseName: "Double Side Kick",
    src: "https://www.youtube.com/watch?v=RFcZ-Khz0pY",
  },
  {
    key: "Deep Cross Chops",
    value: "Deep Cross Chops",
    text: "Deep Cross Chops",
    ExerciseName: "Deep Cross Chops",
    src: "https://www.youtube.com/watch?v=DQtHY0bQ4N8",
  },
  {
    key: "Cross Chops",
    value: "Cross Chops",
    text: "Cross Chops",
    ExerciseName: "Cross Chops",
    src: "https://www.youtube.com/watch?v=8BaS28MG7mw",
  },
  {
    key: "Bounces",
    value: "Bounces",
    text: "Bounces",
    ExerciseName: "Bounces",
    src: "https://www.youtube.com/watch?v=YLfUEHxYvMw",
  },
  {
    key: "Back Kicks",
    value: "Back Kicks",
    text: "Back Kicks",
    ExerciseName: "Back Kicks",
    src: "https://www.youtube.com/watch?v=4PUZfAYeuBE",
  },
  {
    key: "Archers",
    value: "Archers",
    text: "Archers",
    ExerciseName: "Archers",
    src: "https://www.youtube.com/watch?v=3Qp8BQ0Rcrc",
  },
  {
    key: "Archer Lunges",
    value: "Archer Lunges",
    text: "Archer Lunges",
    ExerciseName: "Archer Lunges",
    src: "https://www.youtube.com/watch?v=v2bj8ijN82w",
  },
  {
    key: "jab + Cross + Squat",
    value: "jab + Cross + Squat",
    text: "jab + Cross + Squat",
    ExerciseName: "jab + Cross + Squat",
    src: "https://www.youtube.com/watch?v=_cUV0rWU92s",
  },
  {
    key: "Backfist + Side Kick",
    value: "Backfist + Side Kick",
    text: "Backfist + Side Kick",
    ExerciseName: "Backfist + Side Kick",
    src: "https://www.youtube.com/watch?v=3YjSjPHGhhI",
  },
  {
    key: "Backfist + Side Kick Side-to-Side",
    value: "Backfist + Side Kick Side-to-Side",
    text: "Backfist + Side Kick Side-to-Side",
    ExerciseName: "Backfist + Side Kick Side-to-Side",
    src: "https://www.youtube.com/watch?v=scAal71n7p8",
  },
  {
    key: "Backfists",
    value: "Backfists",
    text: "Backfists",
    ExerciseName: "Backfists",
    src: "https://www.youtube.com/watch?v=ow2-_7CJUXE",
  },
  {
    key: "Backfists Side-to-Side",
    value: "Backfists Side-to-Side",
    text: "Backfists Side-to-Side",
    ExerciseName: "Backfists Side-to-Side",
    src: "https://www.youtube.com/watch?v=LMZ6IGEUya4",
  },
  {
    key: "Half Squat Rows",
    value: "Half Squat Rows",
    text: "Half Squat Rows",
    ExerciseName: "Half Squat Rows",
    src: "https://www.youtube.com/watch?v=6qSILDd7H94",
  },
  {
    key: "Sit-Ups",
    value: "Sit-Ups",
    text: "Sit-Ups",
    ExerciseName: "Sit-Ups",
    src: "https://www.youtube.com/watch?v=5bOjqyL0PGE",
  },
  {
    key: "Donkey Kicks",
    value: "Donkey Kicks",
    text: "Donkey Kicks",
    ExerciseName: "Donkey Kicks",
    src: "https://www.youtube.com/watch?v=QGiiuBOQn3Y",
  },
  {
    key: "Side Planks",
    value: "Side Planks",
    text: "Side Planks",
    ExerciseName: "Side Planks",
    src: "https://www.youtube.com/watch?v=Fum_2H2cog4",
  },
  {
    key: "Squat + Jumping Jack",
    value: "Squat + Jumping Jack",
    text: "Squat + Jumping Jack",
    ExerciseName: "Squat + Jumping Jack",
    src: "https://www.youtube.com/watch?v=VZF5GWd7t9E",
  },
  {
    key: "Up & Down Planks",
    value: "Up & Down Planks",
    text: "Up & Down Planks",
    ExerciseName: "Up & Down Planks",
    src: "https://www.youtube.com/watch?v=AAPpXm-q7lc",
  },
  {
    key: "Twist Jacks",
    value: "Twist Jacks",
    text: "Twist Jacks",
    ExerciseName: "Twist Jacks",
    src: "https://www.youtube.com/watch?v=fR_aMGh_F60",
  },
  {
    key: "Toe Taps",
    value: "Toe Taps",
    text: "Toe Taps",
    ExerciseName: "Toe Taps",
    src: "https://www.youtube.com/watch?v=BY2pl7rltUY",
  },
  {
    key: "Toe Tap Hops",
    value: "Toe Tap Hops",
    text: "Toe Tap Hops",
    ExerciseName: "Toe Tap Hops",
    src: "https://www.youtube.com/watch?v=wTfWbsQql1o",
  },
  {
    key: "Thigh Taps",
    value: "Thigh Taps",
    text: "Thigh Taps",
    ExerciseName: "Thigh Taps",
    src: "https://www.youtube.com/watch?v=sgc_gNStBqc",
  },
  {
    key: "Superman",
    value: "Superman",
    text: "Superman",
    ExerciseName: "Superman",
    src: "https://www.youtube.com/watch?v=67rgxYNKbZY",
  },
  {
    key: "Straight Leg Bounds",
    value: "Straight Leg Bounds",
    text: "Straight Leg Bounds",
    ExerciseName: "Straight Leg Bounds",
    src: "https://www.youtube.com/watch?v=NYH6L2doDm4",
  },
  {
    key: "Dynamic Squats",
    value: "Dynamic Squats",
    text: "Dynamic Squats",
    ExerciseName: "Dynamic Squats",
    src: "https://www.youtube.com/watch?v=EHUeE1ShiYU",
  },
  {
    key: "Squats",
    value: "Squats",
    text: "Squats",
    ExerciseName: "Squats",
    src: "https://www.youtube.com/watch?v=Zqc_lc93hak",
  },
  {
    key: "Slow Climbers",
    value: "Slow Climbers",
    text: "Slow Climbers",
    ExerciseName: "Slow Climbers",
    src: "https://www.youtube.com/watch?v=WixPjH4Y5tw",
  },
  {
    key: "Sit-Ups v2",
    value: "Sit-Ups v2",
    text: "Sit-Ups v2",
    ExerciseName: "Sit-Ups v2",
    src: "https://www.youtube.com/watch?v=srkZvYI9brM",
  },
  {
    key: "Sitting Twists",
    value: "Sitting Twists",
    text: "Sitting Twists",
    ExerciseName: "Sitting Twists",
    src: "https://www.youtube.com/watch?v=l2XsG9W5rYo",
  },
  {
    key: "Sit-Outs",
    value: "Sit-Outs",
    text: "Sit-Outs",
    ExerciseName: "Sit-Outs",
    src: "https://www.youtube.com/watch?v=RvDPD_hWX6E",
  },
  {
    key: "Side-to-Side Jumps",
    value: "Side-to-Side Jumps",
    text: "Side-to-Side Jumps",
    ExerciseName: "Side-to-Side Jumps",
    src: "https://www.youtube.com/watch?v=oHq-TC9TPpI",
  },
  {
    key: "Side Plank Rotations",
    value: "Side Plank Rotations",
    text: "Side Plank Rotations",
    ExerciseName: "Side Plank Rotations",
    src: "https://www.youtube.com/watch?v=RrXJTIxyiC8",
  },
  {
    key: "Side Leg Raises",
    value: "Side Leg Raises",
    text: "Side Leg Raises",
    ExerciseName: "Side Leg Raises",
    src: "https://www.youtube.com/watch?v=H8RrfDOLiZU",
  },
  {
    key: "Side Bridges",
    value: "Side Bridges",
    text: "Side Bridges",
    ExerciseName: "Side Bridges",
    src: "https://www.youtube.com/watch?v=xMtCZE6rEiA",
  },
  {
    key: "Shoulder Taps",
    value: "Shoulder Taps",
    text: "Shoulder Taps",
    ExerciseName: "Shoulder Taps",
    src: "https://www.youtube.com/watch?v=gWHQpMUd7vw",
  },
  {
    key: "Seal Jacks",
    value: "Seal Jacks",
    text: "Seal Jacks",
    ExerciseName: "Seal Jacks",
    src: "https://www.youtube.com/watch?v=fxrmaUVAajo",
  },
  {
    key: "Seagulls",
    value: "Seagulls",
    text: "Seagulls",
    ExerciseName: "Seagulls",
    src: "https://www.youtube.com/watch?v=HI8GLfsDs3Y",
  },
  {
    key: "Side Leg Swings",
    value: "Side Leg Swings",
    text: "Side Leg Swings",
    ExerciseName: "Side Leg Swings",
    src: "https://www.youtube.com/watch?v=8OeKO4PjTtM",
  },
  {
    key: "Scissors (Arms)",
    value: "Scissors (Arms)",
    text: "Scissors (Arms)",
    ExerciseName: "Scissors (Arms)",
    src: "https://www.youtube.com/watch?v=Cilm0WNRdCo",
  },
  {
    key: "Scissors",
    value: "Scissors",
    text: "Scissors",
    ExerciseName: "Scissors",
    src: "https://www.youtube.com/watch?v=tugL2lM4Syk",
  },
  {
    key: "Scissor Chops",
    value: "Scissor Chops",
    text: "Scissor Chops",
    ExerciseName: "Scissor Chops",
    src: "https://www.youtube.com/watch?v=vvNkomexxcs",
  },
  {
    key: "Reverse Crunches",
    value: "Reverse Crunches",
    text: "Reverse Crunches",
    ExerciseName: "Reverse Crunches",
    src: "https://www.youtube.com/watch?v=QYNZwyDKmhk",
  },
  {
    key: "Reverse Bounds",
    value: "Reverse Bounds",
    text: "Reverse Bounds",
    ExerciseName: "Reverse Bounds",
    src: "https://www.youtube.com/watch?v=aLCQRU7lrRg",
  },
  {
    key: "Plank Step-Outs",
    value: "Plank Step-Outs",
    text: "Plank Step-Outs",
    ExerciseName: "Plank Step-Outs",
    src: "https://www.youtube.com/watch?v=RZU8A539nFg",
  },
  {
    key: "Plank Rotations",
    value: "Plank Rotations",
    text: "Plank Rotations",
    ExerciseName: "Plank Rotations",
    src: "https://www.youtube.com/watch?v=VBd6DBVNUYg",
  },
  {
    key: "Plank Rolls",
    value: "Plank Rolls",
    text: "Plank Rolls",
    ExerciseName: "Plank Rolls",
    src: "https://www.youtube.com/watch?v=t3elxPJ1HU4",
  },
  {
    key: "Plank Leg Raises",
    value: "Plank Leg Raises",
    text: "Plank Leg Raises",
    ExerciseName: "Plank Leg Raises",
    src: "https://www.youtube.com/watch?v=IexgiQZetb8",
  },
  {
    key: "Plank Knee-Ins",
    value: "Plank Knee-Ins",
    text: "Plank Knee-Ins",
    ExerciseName: "Plank Knee-Ins",
    src: "https://www.youtube.com/watch?v=n8KThHwjgkY",
  },
  {
    key: "Plank Jump-Ins",
    value: "Plank Jump-Ins",
    text: "Plank Jump-Ins",
    ExerciseName: "Plank Jump-Ins",
    src: "https://www.youtube.com/watch?v=b-83f_fZ-H0",
  },
  {
    key: "Plank Jacks",
    value: "Plank Jacks",
    text: "Plank Jacks",
    ExerciseName: "Plank Jacks",
    src: "https://www.youtube.com/watch?v=3VpkyIcnT64",
  },
  {
    key: "Planks Into Lunges",
    value: "Planks Into Lunges",
    text: "Planks Into Lunges",
    ExerciseName: "Planks Into Lunges",
    src: "https://www.youtube.com/watch?v=qCE0U9yuJtc",
  },
  {
    key: "Plank Arm Raises",
    value: "Plank Arm Raises",
    text: "Plank Arm Raises",
    ExerciseName: "Plank Arm Raises",
    src: "https://www.youtube.com/watch?v=TyiujJcZHVY",
  },
  {
    key: "Lunges v2",
    value: "Lunges v2",
    text: "Lunges v2",
    ExerciseName: "Lunges v2",
    src: "https://www.youtube.com/watch?v=48PIkHs1c9w",
  },
  {
    key: "Lunges",
    value: "Lunges",
    text: "Lunges",
    ExerciseName: "Lunges",
    src: "https://www.youtube.com/watch?v=UpyDdQjBTa0",
  },
  {
    key: "Knee-to-Elbow Crunches",
    value: "Knee-to-Elbow Crunches",
    text: "Knee-to-Elbow Crunches",
    ExerciseName: "Knee-to-Elbow Crunches",
    src: "https://www.youtube.com/watch?v=wDbRpbJyMu8",
  },
  {
    key: "Jump Squats",
    value: "Jump Squats",
    text: "Jump Squats",
    ExerciseName: "Jump Squats",
    src: "https://www.youtube.com/watch?v=bv7as8mDXLQ",
  },
  {
    key: "Jumps",
    value: "Jumps",
    text: "Jumps",
    ExerciseName: "Jumps",
    src: "https://www.youtube.com/watch?v=bIILw7Bsk_M",
  },
  {
    key: "Jumping Jacks v2",
    value: "Jumping Jacks v2",
    text: "Jumping Jacks v2",
    ExerciseName: "Jumping Jacks v2",
    src: "https://www.youtube.com/watch?v=gG2Z1siSvkk",
  },
  {
    key: "Hundreds",
    value: "Hundreds",
    text: "Hundreds",
    ExerciseName: "Hundreds",
    src: "https://www.youtube.com/watch?v=9wMHvG6QInQ",
  },
  {
    key: "Half Jacks",
    value: "Half Jacks",
    text: "Half Jacks",
    ExerciseName: "Half Jacks",
    src: "https://www.youtube.com/watch?v=F16nHvGbsiw",
  },
  {
    key: "Flutter Kicks",
    value: "Flutter Kicks",
    text: "Flutter Kicks",
    ExerciseName: "Flutter Kicks",
    src: "https://www.youtube.com/watch?v=WRnq49TAv-w",
  },
  {
    key: "Elbow Plank Leg Raises",
    value: "Elbow Plank Leg Raises",
    text: "Elbow Plank Leg Raises",
    ExerciseName: "Elbow Plank Leg Raises",
    src: "https://www.youtube.com/watch?v=Akf3IP0H9fA",
  },
  {
    key: "Elbow Plank Arm Raises",
    value: "Elbow Plank Arm Raises",
    text: "Elbow Plank Arm Raises",
    ExerciseName: "Elbow Plank Arm Raises",
    src: "https://www.youtube.com/watch?v=VFFaS0KKtps",
  },
  {
    key: "Dragon Push-Ups (Slower)",
    value: "Dragon Push-Ups (Slower)",
    text: "Dragon Push-Ups (Slower)",
    ExerciseName: "Dragon Push-Ups (Slower)",
    src: "https://www.youtube.com/watch?v=xE9jmA_FDaA",
  },
  {
    key: "Dragon Push-Ups",
    value: "Dragon Push-Ups",
    text: "Dragon Push-Ups",
    ExerciseName: "Dragon Push-Ups",
    src: "https://www.youtube.com/watch?v=sflrxv53L-o",
  },
  {
    key: "Crunches",
    value: "Crunches",
    text: "Crunches",
    ExerciseName: "Crunches",
    src: "https://www.youtube.com/watch?v=HiRsmHH7psA",
  },
  {
    key: "Climber Taps",
    value: "Climber Taps",
    text: "Climber Taps",
    ExerciseName: "Climber Taps",
    src: "https://www.youtube.com/watch?v=9pBEn_zQhoc",
  },
  {
    key: "Climbers",
    value: "Climbers",
    text: "Climbers",
    ExerciseName: "Climbers",
    src: "https://www.youtube.com/watch?v=w2iTOneGPdU",
  },
  {
    key: "Calf Raises",
    value: "Calf Raises",
    text: "Calf Raises",
    ExerciseName: "Calf Raises",
    src: "https://www.youtube.com/watch?v=UV8gOrHmuKc",
  },
  {
    key: "Butt Kicks",
    value: "Butt Kicks",
    text: "Butt Kicks",
    ExerciseName: "Butt Kicks",
    src: "https://www.youtube.com/watch?v=lVZi-AwxLPo",
  },
  {
    key: "Bridge v2",
    value: "Bridge v2",
    text: "Bridge v2",
    ExerciseName: "Bridge v2",
    src: "https://www.youtube.com/watch?v=N1Ikv4MrwI0",
  },
  {
    key: "Bridge Taps",
    value: "Bridge Taps",
    text: "Bridge Taps",
    ExerciseName: "Bridge Taps",
    src: "https://www.youtube.com/watch?v=8lmxy4QKLbo",
  },
  {
    key: "Bridges",
    value: "Bridges",
    text: "Bridges",
    ExerciseName: "Bridges",
    src: "https://www.youtube.com/watch?v=N48d7sm8dbU",
  },
  {
    key: "Body Saw",
    value: "Body Saw",
    text: "Body Saw",
    ExerciseName: "Body Saw",
    src: "https://www.youtube.com/watch?v=ZTN2mCuYi2Y",
  },
  {
    key: "Alternative Arm / Leg Raises",
    value: "Alternative Arm / Leg Raises",
    text: "Alternative Arm / Leg Raises",
    ExerciseName: "Alternative Arm / Leg Raises",
    src: "https://www.youtube.com/watch?v=DFk3yGZv62U",
  },
  {
    key: "Army Crawl",
    value: "Army Crawl",
    text: "Army Crawl",
    ExerciseName: "Army Crawl",
    src: "https://www.youtube.com/watch?v=bR-XzXen9xU",
  },
  {
    key: "Bear Crawl",
    value: "Bear Crawl",
    text: "Bear Crawl",
    ExerciseName: "Bear Crawl",
    src: "https://www.youtube.com/watch?v=bfT5TaRFKQw",
  },
  {
    key: "Accordion Push-Ups",
    value: "Accordion Push-Ups",
    text: "Accordion Push-Ups",
    ExerciseName: "Accordion Push-Ups",
    src: "https://www.youtube.com/watch?v=01xjUrLWWrk",
  },
  {
    key: "Axe Kicks",
    value: "Axe Kicks",
    text: "Axe Kicks",
    ExerciseName: "Axe Kicks",
    src: "https://www.youtube.com/watch?v=7mOGylDcQH4",
  },
  {
    key: "Push Kicks",
    value: "Push Kicks",
    text: "Push Kicks",
    ExerciseName: "Push Kicks",
    src: "https://www.youtube.com/watch?v=PEjlGr3FTrg",
  },
  {
    key: "Hook Kicks / Back Leg",
    value: "Hook Kicks / Back Leg",
    text: "Hook Kicks / Back Leg",
    ExerciseName: "Hook Kicks / Back Leg",
    src: "https://www.youtube.com/watch?v=qRahlIC3EQE",
  },
  {
    key: "Hook Kicks",
    value: "Hook Kicks",
    text: "Hook Kicks",
    ExerciseName: "Hook Kicks",
    src: "https://www.youtube.com/watch?v=3HzaIMk--vk",
  },
  {
    key: "Front Kicks / Back Leg",
    value: "Front Kicks / Back Leg",
    text: "Front Kicks / Back Leg",
    ExerciseName: "Front Kicks / Back Leg",
    src: "https://www.youtube.com/watch?v=JdBDa6XAqJc",
  },
  {
    key: "Front Kicks",
    value: "Front Kicks",
    text: "Front Kicks",
    ExerciseName: "Front Kicks",
    src: "https://www.youtube.com/watch?v=Pktkg8EFLfk",
  },
  {
    key: "Double Turning Kicks / Back Leg / Low & Mid",
    value: "Double Turning Kicks / Back Leg / Low & Mid",
    text: "Double Turning Kicks / Back Leg / Low & Mid",
    ExerciseName: "Double Turning Kicks / Back Leg / Low & Mid",
    src: "https://www.youtube.com/watch?v=AF8cjZg6E9c",
  },
  {
    key: "Double Turning Kicks / Low & Mid Height",
    value: "Double Turning Kicks / Low & Mid Height",
    text: "Double Turning Kicks / Low & Mid Height",
    ExerciseName: "Double Turning Kicks / Low & Mid Height",
    src: "https://www.youtube.com/watch?v=sIhscm9C93c",
  },
  {
    key: "Turning Kicks / Side-to-Side",
    value: "Turning Kicks / Side-to-Side",
    text: "Turning Kicks / Side-to-Side",
    ExerciseName: "Turning Kicks / Side-to-Side",
    src: "https://www.youtube.com/watch?v=kYVhL1HOOjE",
  },
  {
    key: "Turning Kicks / Back Leg",
    value: "Turning Kicks / Back Leg",
    text: "Turning Kicks / Back Leg",
    ExerciseName: "Turning Kicks / Back Leg",
    src: "https://www.youtube.com/watch?v=HC46YYIaeVo",
  },
  {
    key: "Turning Kicks",
    value: "Turning Kicks",
    text: "Turning Kicks",
    ExerciseName: "Turning Kicks",
    src: "https://www.youtube.com/watch?v=ZqQY9SlJiiQ",
  },
  {
    key: "Double Side Kicks / Low &  Mid Height",
    value: "Double Side Kicks / Low &  Mid Height",
    text: "Double Side Kicks / Low &  Mid Height",
    ExerciseName: "Double Side Kicks / Low &  Mid Height",
    src: "https://www.youtube.com/watch?v=zZz30fcHbvE",
  },
  {
    key: "Side Kicks / Side-to-Side",
    value: "Side Kicks / Side-to-Side",
    text: "Side Kicks / Side-to-Side",
    ExerciseName: "Side Kicks / Side-to-Side",
    src: "https://www.youtube.com/watch?v=XrM3OXvYmmQ",
  },
  {
    key: "Side Kicks / Back Leg",
    value: "Side Kicks / Back Leg",
    text: "Side Kicks / Back Leg",
    ExerciseName: "Side Kicks / Back Leg",
    src: "https://www.youtube.com/watch?v=4BSRusbjebw",
  },
  {
    key: "Side Kicks",
    value: "Side Kicks",
    text: "Side Kicks",
    ExerciseName: "Side Kicks",
    src: "https://www.youtube.com/watch?v=eGH70NGZ1po",
  },
  {
    key: "Side Splits",
    value: "Side Splits",
    text: "Side Splits",
    ExerciseName: "Side Splits",
    src: "https://www.youtube.com/watch?v=HAQvQXovwuo",
  },
  {
    key: "Hop Heel Clicks",
    value: "Hop Heel Clicks",
    text: "Hop Heel Clicks",
    ExerciseName: "Hop Heel Clicks",
    src: "https://www.youtube.com/watch?v=4XcGTvcSRxY",
  },
];
