export const exercises = [
  {
    key: "Step Jacks",
    value: "Step Jacks",
    text: "Step Jacks",
    ExerciseName: "Step Jacks",
    src: "https://www.youtube.com/watch?v=JHdVMkRBuRA",
  },
  {
    key: "Raised Arms Circles",
    value: "Raised Arms Circles",
    text: "Raised Arms Circles",
    ExerciseName: "Raised Arms Circles",
    src: "https://www.youtube.com/watch?v=D40wm6vbI_0",
  },
  {
    key: "Bicep Extensions",
    value: "Bicep Extensions",
    text: "Bicep Extensions",
    ExerciseName: "Bicep Extensions",
    src: "https://www.youtube.com/watch?v=l5dfkW6w5qI",
  },
  {
    key: "Standing Shoulder Taps",
    value: "Standing Shoulder Taps",
    text: "Standing Shoulder Taps",
    ExerciseName: "Standing Shoulder Taps",
    src: "https://www.youtube.com/watch?v=j9NPpdmG89s",
  },
  {
    key: "Micro Chest Expansions",
    value: "Micro Chest Expansions",
    text: "Micro Chest Expansions",
    ExerciseName: "Micro Chest Expansions",
    src: "https://www.youtube.com/watch?v=77FNvJPaVjs",
  },
  {
    key: "Side Bends",
    value: "Side Bends",
    text: "Side Bends",
    ExerciseName: "Side Bends",
    src: "https://www.youtube.com/watch?v=uWLFCRHU0Og",
  },
  {
    key: "Stacked Push-Ups",
    value: "Stacked Push-Ups",
    text: "Stacked Push-Ups",
    ExerciseName: "Stacked Push-Ups",
    src: "https://www.youtube.com/watch?v=YEDCkJ-Uv7c",
  },
  {
    key: "Staggered Push-Ups",
    value: "Staggered Push-Ups",
    text: "Staggered Push-Ups",
    ExerciseName: "Staggered Push-Ups",
    src: "https://www.youtube.com/watch?v=FO3MZNFQS28",
  },
  {
    key: "Diver Push-Ups",
    value: "Diver Push-Ups",
    text: "Diver Push-Ups",
    ExerciseName: "Diver Push-Ups",
    src: "https://www.youtube.com/watch?v=tQbcc27zjiA",
  },
  {
    key: "Raised Leg Push-Ups",
    value: "Raised Leg Push-Ups",
    text: "Raised Leg Push-Ups",
    ExerciseName: "Raised Leg Push-Ups",
    src: "https://www.youtube.com/watch?v=XA8T_bHHkl0",
  },
  {
    key: "Squat Hold Calf Raises",
    value: "Squat Hold Calf Raises",
    text: "Squat Hold Calf Raises",
    ExerciseName: "Squat Hold Calf Raises",
    src: "https://www.youtube.com/watch?v=wYoE11arXIw",
  },
  {
    key: "Squat Cross Steps",
    value: "Squat Cross Steps",
    text: "Squat Cross Steps",
    ExerciseName: "Squat Cross Steps",
    src: "https://www.youtube.com/watch?v=8JLMA-Z5S1o",
  },
  {
    key: "Sprinter Lunges",
    value: "Sprinter Lunges",
    text: "Sprinter Lunges",
    ExerciseName: "Sprinter Lunges",
    src: "https://www.youtube.com/watch?v=kaFs0XcgUfo",
  },
  {
    key: "Split Jacks",
    value: "Split Jacks",
    text: "Split Jacks",
    ExerciseName: "Split Jacks",
    src: "https://www.youtube.com/watch?v=83cVgok6KrI",
  },
  {
    key: "Reverse Plank Kicks",
    value: "Reverse Plank Kicks",
    text: "Reverse Plank Kicks",
    ExerciseName: "Reverse Plank Kicks",
    src: "https://www.youtube.com/watch?v=3eIPmCV_1HM",
  },
  {
    key: "Reverse Lunges",
    value: "Reverse Lunges",
    text: "Reverse Lunges",
    ExerciseName: "Reverse Lunges",
    src: "https://www.youtube.com/watch?v=-Q_2HR5OhEY",
  },
  {
    key: "Reverse Lunge Knee Taps",
    value: "Reverse Lunge Knee Taps",
    text: "Reverse Lunge Knee Taps",
    ExerciseName: "Reverse Lunge Knee Taps",
    src: "https://www.youtube.com/watch?v=PnjYoDKj32c",
  },
  {
    key: "March Jacks",
    value: "March Jacks",
    text: "March Jacks",
    ExerciseName: "March Jacks",
    src: "https://www.youtube.com/watch?v=qIDC7Ttfjn0",
  },
  {
    key: "Lunge Step-Ups",
    value: "Lunge Step-Ups",
    text: "Lunge Step-Ups",
    ExerciseName: "Lunge Step-Ups",
    src: "https://www.youtube.com/watch?v=KM6-6xTRpow",
  },
  {
    key: "Lasso Twists",
    value: "Lasso Twists",
    text: "Lasso Twists",
    ExerciseName: "Lasso Twists",
    src: "https://www.youtube.com/watch?v=OjFo600wGK4",
  },
  {
    key: "Jump Knee-Tucks",
    value: "Jump Knee-Tucks",
    text: "Jump Knee-Tucks",
    ExerciseName: "Jump Knee-Tucks",
    src: "https://www.youtube.com/watch?v=ArZXCfbjxWs",
  },
  {
    key: "Side-to-Side Hops - feet Together",
    value: "Side-to-Side Hops - feet Together",
    text: "Side-to-Side Hops - feet Together",
    ExerciseName: "Side-to-Side Hops - feet Together",
    src: "https://www.youtube.com/watch?v=0ZxLHEKzBp4",
  },
  {
    key: "Side-to-Side Hops",
    value: "Side-to-Side Hops",
    text: "Side-to-Side Hops",
    ExerciseName: "Side-to-Side Hops",
    src: "https://www.youtube.com/watch?v=NTqBhdYuT6M",
  },
  {
    key: "Hops on the Spot",
    value: "Hops on the Spot",
    text: "Hops on the Spot",
    ExerciseName: "Hops on the Spot",
    src: "https://www.youtube.com/watch?v=42DO_okRZ1Q",
  },
  {
    key: "Hops - Ape",
    value: "Hops - Ape",
    text: "Hops - Ape",
    ExerciseName: "Hops - Ape",
    src: "https://www.youtube.com/watch?v=XG6eVjFp0hw",
  },
];
